server:
  port: 8087
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  messages:
    basename: messages

#logging:
  #level:
    #org.springframework : debug

management:
  endpoints:
    web:
      exposure:
        include: "*"


